Workaround for SSL exception when downloading models from zenodo.org
Downloading from Zenodo sometimes resulted in the following exception:
java.security.cert.CertificateException: No subject alternative DNS name matching zenodo.org found

* There is a workaround for this exception described here: https://stackoverflow.com/questions/19540289/how-to-fix-the-java-security-cert-certificateexception-no-subject-alternative
* The workaround seems to disable the secure connection. However, since we are downloading data that is public anyway from Zenodo this may not be an issue here